### ISSUE TITLE
More optics

### ISSUE THREAD

**Issue by kozross** [kozross/text-ascii#10]
Currently we only have `Prism`s, but there's probably more we could add. Some advice from an optics expert would be good. 

Hint @emilypi hint.

**Comment by emilypi** [comment]
The *audacity* to tag me! I'll look at it this weekend :)

**Comment by kozross** [comment]
I am, if nothing else, _audacious_.

**Comment by kozross** [comment]
Blocked by [this issue](https://github.com/well-typed/optics/issues/400). We could roll this by hand, but it's probably easier not to.

**Comment by kozross** [comment]
Done with 0e6dda5.
