### ISSUE TITLE
Replace Text-sourced functions with something more general

### ISSUE THREAD

**Issue by kozross** [kozross/text-ascii#22]
For example, we currently have this:

```haskell
fromText :: Text -> Maybe AsciiText
```

This necessitates a dependency on `text`, which is otherwise basically not used for anything. Additionally, this is fairly narrow, for no good reason - unlike `fromByteString`, which can be non-copying, `fromText` forces us to copy either way.

A more general solution would be something like:

```haskell
fromString :: (IsString a) => a -> Maybe AsciiText
```

This is in fact strictly more general, and would allow us to shed a dependency on `text`. It has some unpleasant overlaps (since techically, `IsString ByteString` exists), but it seems to be worthwhile.

**Comment by Kleidukos** [comment]
in the end, if `fromByteString @ByteString === id`, it's not really a problem?

**Comment by kozross** [comment]
You mean `fromString @ByteString == id`? If so, then yes (assuming no invalid bytes), but it's just inefficient. I guess that's for the docs to note. There's also the 'conflation of encoding with conversion' as per #23, but that's something I can't do a lot about (the `IsString ByteString` instance kinda forces this).

**Comment by kozross** [comment]
Done with 09d81fb.
